---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: 172.16.194.131
  labels:
    role: lb
    zone: black
    namespace: production
    project: example
    ip: 172.16.194.131
spec:
  node: lb01
  interfaceName: eth1
  expectedIPs: [172.16.194.131]
