---
- hosts: manage_aio
  become: true
  strategy: linear
  roles:
    - {role: manage_aio, tags: manage_aio}

- hosts: bamboofw_agent
  become: true
  strategy: linear
  roles:
    - {role: bamboofw_agent, tags: bamboofw_agent}
